CREATE TABLE IF NOT EXISTS `Customers` (
  `CustomerID` INT AUTO_INCREMENT PRIMARY KEY,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(150) UNIQUE NOT NULL,
  `Phone` VARCHAR(20),
  `ShippingAddress` VARCHAR(255),
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `IsActive` BOOLEAN DEFAULT TRUE
)