CREATE TABLE IF NOT EXISTS `Procurement_Staff` (
  `StaffID` INT AUTO_INCREMENT PRIMARY KEY,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(150) UNIQUE NOT NULL,
  `Phone` VARCHAR(20),
  `Role` VARCHAR(50),
  `IsActive` BOOLEAN DEFAULT TRUE
)