CREATE TABLE IF NOT EXISTS `Product_Categories` (
  `CategoryID` INT AUTO_INCREMENT PRIMARY KEY,
  `CategoryName` VARCHAR(100) NOT NULL,
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `IsActive` BOOLEAN DEFAULT TRUE
)